name: Build and Release Linux Binary

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v2
        with:
          rust-version: stable

      - name: Build
        run: cargo build --release

      - name: Upload Linux Binary
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/healthcalc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
