name: build-linux

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu

      - name: Build release binary for Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Upload release asset to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-unknown-linux-gnu/release/healthcalc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
