name: Release Health Calculator

on:
  push:
    tags:
      - 'V*'  # Works for V20.1.1 and future versions

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      BINARY_NAME: healthcalc
      VERSION: ${GITHUB_REF#refs/tags/}  # Automatically extracts tag (e.g. V20.1.1)

    steps:
      - uses: actions/checkout@v4

      # 1. OFFICIALLY RECOMMENDED RUST INSTALLATION
      - name: Install Rust
        uses: actions-rust-lang/setup-rust@v1
        with:
          rust-version: stable
          components: rustfmt, clippy
          profile: minimal
          cache: true  # Automatic dependency caching

      # 2. ALTERNATIVE OPTION (choose one)
      # - name: Install Rust (alternative)
      #   uses: dtolnay/rust-toolchain@stable
      #   with:
      #     toolchain: stable
      #     targets: x86_64-unknown-linux-musl

      - name: Build Release
        run: |
          cargo build --release
          mkdir -p release
          cp target/release/$BINARY_NAME release/
          tar -czvf $BINARY_NAME-${VERSION}-linux-x64.tar.gz -C release $BINARY_NAME

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}